runtime: python27
threadsafe: true
api_version: 1

skip_files:
- ^(.*/)?.*/angular_material_schematics*/.*$
- ^(.*/)?.*/e2e/.*$
- ^(.*/)?.*/node_modules/.*$
- ^node_modules$
- ^.git

handlers:
- url: /static
  static_dir: static

- url: /((?:main|polyfills|styles|vendor|runtime)(?:\.[a-z0-9]*)?(?:\.js)?(?:\.css)?(?:\.map)?)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/\1
  upload: dist/.*
  application_readable: true

- url: /_ah/api/.*
  secure: always
  script: server.api.application

- url: /.*
  secure: always
  script: server.backend.application

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

env_variables:
  # Provide the below variables with values from the output of
  # 'gcloud endpoints services deploy api-def.yaml' command.
  #
  # The API can be examined by going to:
  # https://developers.google.com/apis-explorer/?base=https://ng-md-gae-boilerplate.appspot.com/_ah/api#p/
  ENDPOINTS_SERVICE_NAME: ng-md-gae-boilerplate.appspot.com
  ENDPOINTS_SERVICE_VERSION: 2018-07-05r2

