runtime: python27
api_version: 1
threadsafe: true

libraries:
# - name: pycrypto
#   version: latest
# - name: endpoints
#   version: 1.0
# - name: ssl
#   version: latest
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

env_variables:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy swagger.json' command.
  ENDPOINTS_SERVICE_NAME: ng-md-gae-boilerplate.appspot.com
  # ENDPOINTS_SERVICE_VERSION: 2018-06-21r0

handlers:
- url: /static
  static_dir: static

- url: /((?:main|polyfills|styles|vendor|runtime)(?:\.[a-z0-9]*)?(?:\.js)?(?:\.css)?(?:\.map)?)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/\1
  upload: dist/.*
  application_readable: true

# url below must be /_ah/spi/.*
# although the calls are like
# /_ah/api/.*
# - url: /_ah/spi/.*
#   secure: always
#   script: server.api.application

- url: /_ah/api/.*
  secure: always
  script: server.api.application

- url: /.*
  secure: always
  script: server.backend.application

skip_files:
- ^(.*/)?.*/angular_material_schematics*/.*$
- ^(.*/)?.*/e2e/.*$
- ^(.*/)?.*/node_modules/.*$
- ^node_modules$