runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0

handlers:

- url: /((?:main|polyfills|styles|vendor|runtime)(?:\.js)(?:\.map)?)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/\1
  upload: dist/.*
  application_readable: true

# url below must be /_ah/spi/.*
# although the calls are like
# /_ah/api/.*
- url: /_ah/spi/.*
  secure: always
  script: server.api.application

- url: /.*
  secure: always
  script: server.backend.application

skip_files:
- ^(.*/)?.*/angular_material_schematics*/.*$
- ^(.*/)?.*/e2e/.*$
- ^(.*/)?.*/node_modules/.*$
- ^node_modules$